---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sock-monster-secrets
subjects:
  - kind: User
    name: sock-monster 
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]